# PA Opioid Epidemic

In [261]:
import pandas as pd
import numpy as np
import matplotlib as plt
import folium

In [262]:
overdose_dat = 'Overdose_Information_Network_Data_CY_January_2018_-_Current_Monthly_County_State_Police.csv'
county_geo = 'PaCounty2020_01.geojson'

In [263]:
ovd = pd.read_csv(overdose_dat)

In [264]:
df = ovd.drop(['Response Time Desc', 'Revive Action Desc', 'Response Desc', 'Victim County', 'Victim OD Drug ID', 'Third Party Admin Desc', 'Administration ID', 'Dose Count', 'Dose Unit', 'Dose Desc', 'Incident ID', 'Victim State', 'Incident State', 'Victim County Latitude and Longitude', 'Incident County Latitude and Longitude', 'Victim ID', 'Victim County FIPS Code', 'Incident County FIPS Code', 'Victim County Latitude', 'Victim County Longitude'], axis=1)
df = df.rename(columns={"Survive": "Survived", "Ethnicity Desc": "Hispanic", "Accidental Exposure": "Accident", "Age Range": "Age", "Naloxone Administered": "Naloxone", "Incident County Longitude": "Longitude", "Incident County Latitude": "Latitude", "Susp OD Drug Desc": "Drug", "Gender Desc": "Gender", "Incident Date": "Date", "Incident Time": "Time", "Incident County Name": "County"})
df['Date'] = df['Date'] + ":" + df['Time']
df = df.drop(['Time'], axis=1)

In [265]:
df['Date'] = df['Date'].replace(to_replace=r'\/', value=':', regex=True)
df['Date'] = pd.to_datetime(df['Date'], format='%m:%d:%Y:%H:%M:%S')

In [266]:
df['Age'] = df['Age'].replace(to_replace=r'\s\-\s', value='-', regex=True)
df['Age'] = df['Age'].replace(to_replace=r'14-Oct', value='0-14')
df['Age'] = df['Age'].replace(to_replace=r'0-9', value='0-14')
df['Age'] = df['Age'].replace(to_replace=r'80-*', value='80+')

In [267]:
df['Gender'] = df['Gender'].replace(to_replace=r'Male', value='M')
df['Gender'] = df['Gender'].replace(to_replace=r'Female', value='F')
df['Gender'] = df['Gender'].replace(to_replace=r'Unknown', value='U')

In [268]:
df['Accident'] = df['Accident'].replace(to_replace=r'N', value='0')
df['Accident'] = df['Accident'].replace(to_replace=r'Y', value='1')
df['Accident'] = df['Accident'].astype(int)

In [269]:
df['Naloxone'] = df['Naloxone'].replace(to_replace=r'N', value='0')
df['Naloxone'] = df['Naloxone'].replace(to_replace=r'Y', value='1')
df['Naloxone'] = df['Naloxone'].astype(int)

In [270]:
df['Hispanic'] = df['Hispanic'].replace(to_replace=r'Not Hispanic', value='0')
df['Hispanic'] = df['Hispanic'].replace(to_replace=r'Hispanic', value='1')
df['Hispanic'] = df['Hispanic'].replace(to_replace=r'Unknown', value='0')
df['Hispanic'] = df['Hispanic'].replace(to_replace=r'Mongolian', value='0')
df['Hispanic'] = df['Hispanic'].astype(int)

In [271]:
df['Race'] = df['Race'].replace(to_replace=r'Unknown', value='Other')
df['Race'] = df['Race'].replace(to_replace=r'Asian or Pacific Islander', value='Other')
df['Race'] = df['Race'].replace(to_replace=r'American Indian or Alaskan Native', value='Other')

In [272]:
df['Drug'] = df['Drug'].str.lower()
df['Drug'] = df['Drug'].replace(to_replace=r'benzodiazepines (i.e.valium, xanax, ativan, etc)', value='benzodiazepines')
df['Drug'] = df['Drug'].replace(to_replace=r'buprenorphine (i.e. suboxone, sublocade, subutex, butrans, buprenex, etc)', value='buprenorphine')
df['Drug'] = df['Drug'].replace(to_replace=r'barbiturates (i.e. amytal, nembutal, etc)', value='barbiturates')
df['Drug'] = df['Drug'].replace(to_replace=r'fentanyl analog/other synthetic opioid', value='fentanyl')

In [273]:
df

,Date,Day,County,Gender,Age,Race,Hispanic,Accident,Drug,Naloxone,Survived,Latitude,Longitude
0,2020-07-02 12:48:00,Thursday,York,M,50-59,White,1,0,heroin,1,Y,39.921925,-76.725761
1,2020-09-20 23:11:00,Sunday,York,M,20-24,White,0,0,fentanyl,1,Y,39.921925,-76.725761
2,2020-09-11 20:00:00,Friday,Union,M,50-59,White,0,0,heroin,0,N,40.964731,-77.064158
3,2020-07-10 21:10:00,Friday,York,M,40-49,White,0,0,fentanyl,1,Y,39.921925,-76.725761
4,2020-06-20 20:52:00,Saturday,York,M,40-49,White,0,0,fentanyl,0,N,39.921925,-76.725761
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23703,2020-12-19 09:44:00,Saturday,Bucks,F,30-39,White,0,0,unknown,1,Y,40.335011,-75.112912
23704,2021-01-13 12:00:00,Wednesday,Montgomery,F,60-69,White,0,0,pharmaceutical opioid,1,Y,40.209899,-75.372520
23705,2020-12-23 11:47:00,Wednesday,Berks,M,25-29,White,0,0,heroin,1,Y,40.419396,-75.930773
23706,2020-12-20 13:40:00,Sunday,Berks,F,20-24,White,1,0,other,0,Y,40.419396,-75.930773
23707,2021-01-12 18:15:00,Tuesday,Luzerne,F,40-49,White,0,0,heroin,1,U,41.178364,-75.991996